### PR TITLE
[WIP] Adding UWP support and test project

### PR DESCRIPTION
**Pull request by jtaubensee**

### CODE REVIEW

**Comment by jtaubensee** [comment]
@onovotny - Any idea what this error would be? I'm guessing this is a shot in the dark as there really is no description as to what the problem is.

2017-01-18_12h09_34

**Comment by jtaubensee** [comment]
@terrajobst - Do you happen to know what would cause the error that we are seeing? VS showing "Length cannot be less than zero"?

When I run `dotnet build` from the directory, I see this:

```
Microsoft.Azure.Relay.UnitTests.UWP\App.xaml.cs(6,32): error CS0012:
The type 'Application' is defined in an assembly that is not referenced. 
You must add a reference to assembly 
'Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
```

Is that a valid package that I can just add a reference to? I dont see it in NuGet.

**Comment by onovotny** [comment]
@jtaubensee I can try to take a look tonight or tomorrow

**Comment by jtaubensee** [comment]
Thanks @onovotny, I appreciate your help!

**Comment by jtaubensee** [comment]
I'm going to close this for now, but leave the corresponding issue open

**Pull request closed without merging**
