### PR TITLE
Updating project to VS 2017 and build scripts

### PR DESCRIPTION
**Pull request by jtaubensee**
## Description
* Updated project to Visual Studio 2017
* Updated build scripts
  * Can be run locally with code coverage report
* Changed appveyor build to separate jobs for runtimes

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [x] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [x] If applicable, the public code is properly documented.
- [x] Pull request includes test coverage for the included changes.
- [x] The code builds without any errors.

### CODE REVIEW

**Comment by jtaubensee** [comment]
@dstuckims - I know we've talked about this before, but do you know what this should be?

https://ci.appveyor.com/project/jtaubensee/azure-relay-dotnet/build/1.0.1/job/24vmh3p9dxs2qmd5#L150

Here's the tl;dr, its one exception in net451, and another in .net core.
```
Expected: typeof(Microsoft.Azure.Relay.RelayException)
Actual:   typeof(Microsoft.Azure.Relay.EndpointNotFoundException): Endpoint does not exist.
```

**Comment by dlstucki** [comment]
My concern here is with these changes the tests no longer show up in Visual Studio's Test Explorer.

**Comment by dlstucki** [comment]
@jtaubensee, if you run the tests do they actually start up and make it into the project's test code (even if it throws due to the env variable missing)? I can't get things to work unless I change the project to target netcoreapp1.1:
`!>    <TargetFrameworks>netcoreapp1.1;net46</TargetFrameworks>`

I think I may simply be missing `Microsoft.NETCore.App, version '1.0.4'` but I can't figure out where to install that from.

**Comment by jtaubensee** [comment]
@dlstucki - FYI, I don't think that the Appveyor build is ever going to complete... It was still on my account, but since I don't have the same access, things stopped working a while ago. Let me know if you would like help setting it up again.

**Comment by dlstucki** [comment]
Thanks, I created an appveyor account, a project for this repo, checked some boxes you pointed out in the OneNote you sent for knowledge transfer, now I'm stuck on the encrypted secrets part.

**Comment by jtaubensee** [comment]
The secrets are encrypted on a per account basis. So, since the account has changed, you will also need to update the credentials. You can get the credentials from the Azure AD app, and re-encrypt them for your account using: https://www.appveyor.com/docs/how-to/secure-files/#decrypting-files-during-an-appveyor-build.

In case you are in the [.NET Slack group](https://aspnetcore.slack.com/), ([sign up here](http://tattoocoder.com/aspnet-slack-sign-up/)) you can reach me @jtaubensee

Then to update the readme, just change `https://ci.appveyor.com/project/jtaubensee/azure-relay-dotnet/branch/master` to your username.

**Pull request merged**
